# Generated by Django 5.0.6 on 2024-06-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paymentorder_paymentorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='card_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
