# Generated by Django 5.0.6 on 2024-06-01 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_paymentorder_shipping_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='shipping_address',
            field=models.TextField(default=' ', max_length=15000),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='card_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='card_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
